### ISSUE TITLE
How do I know if microui consumed an event?

### ISSUE THREAD

**Issue by prideout** [rxi/microui#18]
If the user drags a microui slider in a window, I don't want the drag to affect the content underneath the window.  imgui has `WantCaptureKeyboard`, `WantCaptureMouse`, etc for this purpose but I can't find the corollary mechanism in microui.

By the way thanks for this library, it's truly beautiful.

**Comment by prideout** [comment]
I *think* this can be achieved by checking the nullness of `hover_root` after defining the UI?

**Comment by rxi** [comment]
If `ctx->focus` is non-zero you can assume microui is capturing keyboard events, if `ctx->hover_root` is non-zero you can assume microui is capturing mouse events. If you process the events for the underlying content *after* the call to `mu_end()` you should be able to use `ctx->focus` for both keyboard and mouse. Thanks for the kind words!
