### ISSUE TITLE
About GL_ALPHA

### ISSUE THREAD

**Issue by heitaoflower** [rxi/microui#2]
Hi , your deom very well running on my project.

However, I encounter some color format issure, GL_ALPHA always invalid, reported by 1281. 
GL_RED is ok, but the visual effect not correct.

the context I used is GLFW not SDL.

Do you have any idea ? thanks.

`glTexImage2D(GL_TEXTURE_2D, 0, GL_RED, ATLAS_WIDTH, ATLAS_HEIGHT, 0, GL_ALPHA, GL_UNSIGNED_BYTE, atlas_texture);`

**Comment by heitaoflower** [comment]
I try to use glfw rendering content, but alway nothing presented. what is the difference between A and B ?
thank you.

**Comment by beetaa** [comment]
@heitaoflower hi, I am new on microui with glfw, how can you mix these together? and the render backend code. thank you.
