### ISSUE TITLE
DirectX 9 

### ISSUE THREAD

**Issue by dzonerzy** [rxi/microui#38]
Would microui works with DirectX ?

**Comment by rxi** [comment]
Microui doesn't do any rendering of its own, this is expected to be provided by the user -- thus it will work with any renderer (be this OpenGL, DirectX, software rendering, etc.) provided it can draw rectangles and text.

**Comment by dzonerzy** [comment]
Would be possible to provide same examples using DirectX? I think that would help not only me

**Comment by g012** [comment]
Check dear ImGui project, it has renderers for direct 3d, easily
transposable to microui.
