### ISSUE TITLE
Font Question

### ISSUE THREAD

**Issue by MungoBerry** [rxi/microui#4]
Hi,

How can I use custom font ?
How can I create my atlas.inl ?

Thank you.

**Comment by rxi** [comment]
The demo program and its renderer are meant only as a small example of how the library should be used. In real projects you are expected to bring your own code for rendering rectangles, icons and text. Alternatively you could use a library like [nanovg](https://github.com/memononen/nanovg) for rendering.

Once you're set up you can switch fonts by changing the `ctx->style->font` value. This value will be passed to the resultant `MU_COMMAND_TEXT` commands for all subsequently rendered text.
