### ISSUE TITLE
Hash function "Cannot convert from 'const void *' to 'const unsigned char *'"

### ISSUE THREAD

**Issue by WillCecil** [rxi/microui#42]
I'm running into an issue when building microui in a C++ project in visual studio 2019.

The two errors that show are one in the hash() function: "Cannot convert from 'const void *' to 'const unsigned char *'"

And another in the mu_next_command() function: "Cannot convert from 'void *' to 'mu_Command *'"

Any idea what might be going wrong?

**Comment by g012** [comment]
Yes, you're compiling in C++. void* implicit casts are illegal in C++. Compile microui as C (/TC if I recall in VS).

**Comment by WillCecil** [comment]
Ahh, gotcha. Is it possible to compile microui in a C++ project?

**Comment by g012** [comment]
I think yes, just specify /TC on microui C files in the build flags for them (right click on the C files, properties / build options, Compile As -> C).

**Comment by WillCecil** [comment]
Hmm. I'm still running into issues but I don't think it's to do with microui, so I'll close this. Thanks for getting me pointed in the right direction!
