### ISSUE TITLE
Not a bug: thanks for microui :)

### ISSUE THREAD

**Issue by floooh** [rxi/microui#8]
Hi, just wanted to let you know that I've created a little microui sample on top of my cross-platform headers, here's the standard sample running in WebAssembly:

https://floooh.github.io/sokol-html5/wasm/sgl-microui-sapp.html

I need to improve a few input handling things (mobile touch input, and figuring out a better way to map my library's mouse-wheel input to yours), but these are minor things.

Also the default font atlas doesn't look too good on a high-dpi display when rendered at half resolution (I've had the same issues with Dear ImGui when using a TTF font, but Dear ImGui's default font looks fine in such situations, if a bit "low-tec": https://floooh.github.io/sokol-html5/wasm/imgui-sapp.html.

But anyway, these are minor issues, and not an issue with microui. Thanks for that neat little library :)

**Comment by rxi** [comment]
Oh wow! Would it be alright if I added a link to this in the README.md file?

Regarding the font: the demo program and atlas is meant only as a quick example, hence its crudeness; in practise one is expected to bring along their own font rendering.

**Comment by floooh** [comment]
>  Would it be alright if I added a link to this in the README.md file?

Of course :)

**Comment by rxi** [comment]
Thanks!
